config/routes.rb
Fortune::Application.routes.draw do

  resources :sports do
    collection do
      get 'soccer'
      get 'tennis'
    end
  end
  get "jobs/index"

  get "jobs/show"

  get "inquiries/new"

  post "inquiries/create"

  get "ticket_draws/new"

  post "ticket_draws/create"

  get "matches/index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users
  resources :users

  get 'home/legal'
  get 'home/privacy'
  get 'home/about'
  get 'home/contact'
  get 'home/coming_soon'

  get 'sports/soccer'

  get 'results/index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/bet_option.rb
class BetOption < ActiveRecord::Base
  attr_accessible :available_for, :name, :number_of_sub_options
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
  INQUIRY_TYPES = ["Customer Service Complaint", "General Inquiry", "Other"].freeze

  attr_accessible :email, :message, :name, :priority, :inquiry_type, :phone_number
  validates_presence_of :email, :message
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates_inclusion_of :inquiry_type, :in => INQUIRY_TYPES

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :category, :description, :location, :qualifications, :title
end

app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :match_date, :player_one, :player_two, :sport, :tournament

  validates_presence_of :match_date, :player_one, :player_two, :sport, :tournament

  has_one :result
end

app/models/news_viewer.rb
class NewsViewer < ActiveRecord::Base
  attr_accessible :author, :body, :excerpt, :title, :media

  #belongs_to :admin_user
  has_attached_file :media, :styles => { :full => "419x282>" }
end

app/models/result.rb
class Result < ActiveRecord::Base
  attr_accessible :match_id, :score

  belongs_to :match
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  attr_accessible :description, :name, :icon

  has_attached_file :icon

  validates_presence_of :name
  validates_attachment_presence :icon
  validates_attachment_content_type :icon, :content_type => ['image/png', 'image/vnd.microsoft.icon']
end

app/models/ticket_draw.rb
class TicketDraw < ActiveRecord::Base
  attr_accessible :email, :name, :ticket_number
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @matches = Match.all
  end
  def legal
  end

  def privacy
  end

  def about
  end

  def contact
  end

  def coming_soon
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cp(path)
    #"current_page" if current_page?(path)
    if current_page?(path)
      "current-page"
    else
      nil
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def jobs_available?
    if @jobs.length > 0
      true
    else
      false
    end
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/ticket_draws_helper.rb
module TicketDrawsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_all_sports.html.haml
All Sports
%li
  =link_to soccer_sports_path do 
    =image_tag 'sport_icons/ball.ico', :size => '21x21'
    %span Soccer
%li
  =link_to '#' do
    =image_tag 'sport_icons/cricket.ico', :size => '21x21'
    %span Cricket
%li
  =link_to '#' do
    =image_tag 'sport_icons/rugby.ico', :size => '21x21'
    %span Rugby Union'
%li
  =link_to '#' do
    =image_tag 'sport_icons/kolf.ico', :size => '21x21'
    %span Golf
/%li= link_to 'Snooker', '#'
%li
  =link_to '#' do
    =image_tag 'sport_icons/basketball.ico', :size => '21x21'
    %span Basketball
%li
  =link_to('#') do
    =image_tag 'sport_icons/boxing_gloves.ico', :size => '21x21'
    %span Boxing
%li
  =link_to '#' do
    =image_tag 'sport_icons/rugby.ico', :size => '21x21'
    %span Rugby League
%li
  =link_to '#' do
    =image_tag 'sport_icons/volleyball_ball.ico', :size => '21x21'
    %span Volleyball
%li
  =link_to '#' do
    =image_tag 'sport_icons/horse_rider.ico', :size => '21x21'
    %span Horse Racing
%li
  =link_to '#' do
    =image_tag 'sport_icons/icehockey.png', :size => '21x21'
    %span Ice Hockey
%li
  =link_to '#' do
    =image_tag 'sport_icons/toyotagt_one.ico', :size => '21x21'
    %span Formula 1
%li
  = link_to(tennis_sports_path, :title => 'tennis odds') do
    =image_tag 'sport_icons/tennis.ico', :size => '21x21'
    %span Tennis
%li
  =link_to '#' do
    =image_tag 'sport_icons/skiing.png', :size => '21x21'
    %span Alpine Skiing
%li
  =link_to '#' do
    =image_tag 'sport_icons/baseball_ball.ico', :size => '21x21'
    %span Baseball
%li
  =link_to '#' do
    =image_tag 'sport_icons/american_football.ico', :size => '21x21'
    %span American Football
%li
  =link_to '#' do
    =image_tag 'sport_icons/clicknrun.ico', :size => '21x21'
    %span Athletics
%li
  =link_to '#' do
    =image_tag 'sport_icons/table_tennis.ico', :size => '21x21'
    %span Table Tennis
%li
  =link_to '#' do
    =image_tag 'sport_icons/shuttlecock.ico', :size => '21x21'
    %span Badminton
%li
  =link_to '#' do
    =image_tag 'sport_icons/bowling.ico', :size => '21x21'
    %span Bowling
%li
  =link_to '#' do
    =image_tag 'sport_icons/motorcycle.ico', :size => '21x21'
    %span Motorbikes
%li
  =link_to '#' do
    =image_tag 'sport_icons/dart.ico', :size => '21x21'
    %span Darts

app/views/home/_daily_odds.html.haml
%h6 Today's Odds
%table{ :class => 'table' }
  %thead
    %tr
      %th Soccer
      %th &nbsp;
      %th 1
      %th X
      %th 2
  %tbody
    %tr
      %td Date
      %td Player1 v Player2
      %td 1
      %td X
      %td 2
    %tr
      %td 29 Jan 22:45
      %td Man Utd v Arsenal fc
      %td 1.20
      %td 6.30
      %td 9.40
%table{ :class => 'table' }
  %thead
    %tr
      %th Tennis
      %th &nbsp;
      %th 1
      %th X
      %th 2
  %tbody
    %tr
      %td 26 Jan 10:00
      %td R.Federer v A.Murray
      %td 2.85
      %td 3.25
      %td 2.25
    %tr
      %td 24 Jan 09:00
      %td N.Djokovic v D.Ferrer
      %td 1.20
      %td 6.30
      %td 9.40
%table{ :class => 'table' }
  %thead
    %tr
      %th Basket Ball
      %th &nbsp;
      %th 1
      %th X
      %th 2
  %tbody
    %tr
      %td 1 Jan 03:00
      %td NY Knicks v M.Heat
      %td 7.50
      %td 3.67
      %td 2.50

app/views/home/_hot_bets.html.haml
%table{ :class => 'table-dbates' }
  %caption Hot Bets
  %thead 
    %tr 
      %th Time:Date
      %th Match code
      %th First Team Wins
      %th Draw
      %th Second Team Wins
  %tbody
    -#-match.each do |match|
      %tr
        %td{:class => 'match-date'} 
          =match.match_date.hour.to_s + ":" + match.match_date.min.to_s
          =match.match_date.month.to_s + "/" + match.match_date.day.to_s
        %td{:class => 'teams'}=match.player_one + "\s"+ match.player_one_wins.to_s
        %td{:class => 'teams'}=match.players_draw
        %td{:class => 'teams'}=match.player_two + "\s" + match.player_two_wins.to_s 
    %tr
      %td{:class => 'match-date'} 6:00 PM 1/30
      %td{:class => 'teams'}12319
      %td{:class => 'teams'} Tromso 2.70
      %td{:class => 'teams'} 3.20
      %td{:class => 'teams'} Widzow Lodz 2.35
    %tr
      %td{:class => 'match-date'} 3:30 PM 9/1
      %td{:class => 'teams'}12320
      %td{:class => 'teams'} Liverpool FC 2.45
      %td{:class => 'teams'} 3.40
      %td{:class => 'teams'} Manchester United 2.70
    %tr
      %td{:class => 'match-date'} 6:00 PM 9/1
      %td{:class => 'teams'}12321
      %td{:class => 'teams'} Arsenal FC 2.10
      %td{:class => 'teams'} 3.40
      %td{:class => 'teams'} Tottenham Hotspur 3.30
    %tr
      %td{:class => 'match-date'} 1:00 PM 9/1
      %td{:class => 'teams'}12322
      %td{:class => 'teams'} Real Madrid 1.15
      %td{:class => 'teams'} 7.75
      %td{:class => 'teams'} Athletico Bilbao 13.50
    %tr
      %td{:class => 'match-date'} 6:00 PM 9/1
      %td{:class => 'teams'}12323
      %td{:class => 'teams'} Espanyol 2.00
      %td{:class => 'teams'} 3.40
      %td{:class => 'teams'} Real Betis 3.60
    %tr
      %td{:class => 'match-date'} 6:00 PM 9/1
      %td{:class => 'teams'}12323
      %td{:class => 'teams'} Espanyol 2.00
      %td{:class => 'teams'} 3.40
      %td{:class => 'teams'} Real Betis 3.60
    %tr
      %td{:class => 'match-date'} 6:00 PM 9/1
      %td{:class => 'teams'}12323
      %td{:class => 'teams'} Espanyol 2.00
      %td{:class => 'teams'} 3.40
      %td{:class => 'teams'} Real Betis 3.60
    %tr
      %td{:class => 'match-date'} 6:00 PM 9/1
      %td{:class => 'teams'}12323
      %td{:class => 'teams'} Espanyol 2.00
      %td{:class => 'teams'} 3.40
      %td{:class => 'teams'} Real Betis 3.60
    %tr
      %td{:class => 'match-date'} 6:00 PM 9/1
      %td{:class => 'teams'}12323
      %td{:class => 'teams'} Espanyol 2.00
      %td{:class => 'teams'} 3.40
      %td{:class => 'teams'} Real Betis 3.60
    %tr
      %td{:class => 'match-date'} 6:00 PM 9/1
      %td{:class => 'teams'}12323
      %td{:class => 'teams'} Espanyol 2.00
      %td{:class => 'teams'} 3.40
      %td{:class => 'teams'} Real Betis 3.60
    %tr
      %td{:class => 'match-date'} 6:00 PM 9/1
      %td{:class => 'teams'}12323
      %td{:class => 'teams'} Espanyol 2.00
      %td{:class => 'teams'} 3.40
      %td{:class => 'teams'} Real Betis 3.60
    %tr
      %td{:class => 'match-date'} 6:00 PM 9/1
      %td{:class => 'teams'}12323
      %td{:class => 'teams'} Espanyol 2.00
      %td{:class => 'teams'} 3.40
      %td{:class => 'teams'} Real Betis 3.60
    %tr
      %td{:class => 'match-date'} 6:00 PM 9/1
      %td{:class => 'teams'}12323
      %td{:class => 'teams'} Espanyol 2.00
      %td{:class => 'teams'} 3.40
      %td{:class => 'teams'} Real Betis 3.60
    %tr
      %td{:class => 'match-date'} 6:00 PM 9/1
      %td{:class => 'teams'}12323
      %td{:class => 'teams'} Espanyol 2.00
      %td{:class => 'teams'} 3.40
      %td{:class => 'teams'} Real Betis 3.60
    %tr
      %td{:class => 'match-date'} 6:00 PM 9/1
      %td{:class => 'teams'}12323
      %td{:class => 'teams'} Espanyol 2.00
      %td{:class => 'teams'} 3.40
      %td{:class => 'teams'} Real Betis 3.60
    %tr
      %td{:class => 'match-date'} 6:00 PM 9/1
      %td{:class => 'teams'}12323
      %td{:class => 'teams'} Espanyol 2.00
      %td{:class => 'teams'} 3.40
      %td{:class => 'teams'} Real Betis 3.60
    %tr
      %td{:class => 'match-date'} 6:00 PM 9/1
      %td{:class => 'teams'}12323
      %td{:class => 'teams'} Espanyol 2.00
      %td{:class => 'teams'} 3.40
      %td{:class => 'teams'} Real Betis 3.60
    -#
      %tr
        %td{:class => 'match-date'} 6:00 PM 9/1
        %td{:class => 'teams'}12323
        %td{:class => 'teams'} Espanyol 2.00
        %td{:class => 'teams'} 3.40
        %td{:class => 'teams'} Real Betis 3.60
      %tr
        %td{:class => 'match-date'} 6:00 PM 9/1
        %td{:class => 'teams'}12323
        %td{:class => 'teams'} Espanyol 2.00
        %td{:class => 'teams'} 3.40
        %td{:class => 'teams'} Real Betis 3.60
      %tr
        %td{:class => 'match-date'} 6:00 PM 9/1
        %td{:class => 'teams'}12323
        %td{:class => 'teams'} Espanyol 2.00
        %td{:class => 'teams'} 3.40
        %td{:class => 'teams'} Real Betis 3.60
      %tr
        %td{:class => 'match-date'} 6:00 PM 9/1
        %td{:class => 'teams'}12323
        %td{:class => 'teams'} Espanyol 2.00
        %td{:class => 'teams'} 3.40
        %td{:class => 'teams'} Real Betis 3.60
      %tr
        %td{:class => 'match-date'} 6:00 PM 9/1
        %td{:class => 'teams'}12323
        %td{:class => 'teams'} Espanyol 2.00
        %td{:class => 'teams'} 3.40
        %td{:class => 'teams'} Real Betis 3.60

app/views/home/_slider.html.haml
%div{:class => 'slider-wrap'}
  %div{:id => 'main-photo-slider', :class => 'csw'}
    %div{:class => 'panelContainer'}
      %div{:class => 'panel', :title => 'Panel 1'}
        %div{:class => 'wrapper'}
          =image_tag 'slider_images/tempphoto-1.jpg', :alt => 'temp'
          %div{:class => 'photo-meta-data'}
            Photo Credit: <a href="http://flickr.com/photos/astrolondon/2396265240/">Kaustav Bhattacharya</a><br />
            %span
              "Free Tibet" Protest at the Olympic Torch Rally

      %div{:class => 'panel', :title => 'Panel 2'}
        %div{:class => 'wrapper'}
          =image_tag 'slider_images/tempphoto-2.jpg', :alt => 'temp'
          %div{:class => 'photo-meta-data'}
            Chicago Bears at Seattle Seahawks
            %span
              Fifth field goal, overtime win for Seahawks

      %div{:class => 'panel', :title => 'Panel 3'}
        %div{:class => 'wrapper'}
          =image_tag 'slider_images/alonso.jpg', :alt => 'Fernando Alonso'
          %div{:class => 'photo-meta-data'}
            Fernando Alonso of team Ferrari relaxing just before a practice session

      %div{:class => 'panel', :title => 'Panel 4'}
        %div{:class => 'wrapper'}
          =image_tag 'slider_images/nfl.jpg', :alt => 'temp'
          %div{:class => 'photo-meta-data'}
            NFL's divisional playoffs

      %div{:class => 'panel', :title => 'Panel 5'}
        %div{:class => 'wrapper'}
          =image_tag 'slider_images/bryan_baker.jpg', :alt => 'temp'
          %div{:class => 'photo-meta-data'}
            Bryan Baker at the 2012 Wimbledon Championships
            %br
            %span
              An empty span

      %div{:class => 'panel', :title => 'Panel 6'}
        %div{:class => 'wrapper'}
          =image_tag 'slider_images/cr_higuan_benzema.jpg', :alt => 'madrid forwards'
          %div{:class => 'photo-meta-data'}
            Cristiano Ronaldo, Gonzalo Higuan and Karim Benzema

  / TO MAKE THESE THUMBNAILS ACTUALLY WORK, BOTH THE HASH VALUE (#1, ETC.)
  /AND THE CLASS="CROSS-LINK" ARE REQUIRED

  =link_to (image_tag 'slider_images/tempphoto-1thumb.jpg', :class => 'nav-thumb', :alt => 'temp-thumb'), '#1', :class => 'cross-link active-thumb'
  %div{:id => 'movers-row'}
    %div
      =link_to (image_tag 'slider_images/tempphoto-2thumb.jpg', :class => 'nav-thumb', :alt => 'temp-thumb'), '#2', :class => 'cross-link'
    %div
      =link_to (image_tag 'slider_images/alonso.jpg', :class => 'nav-thumb', :alt => 'temp-thumb'), '#3', :class => 'cross-link'
    %div
      =link_to (image_tag 'slider_images/nfl.jpg', :class => 'nav-thumb', :alt => 'temp-thumb'), '#4', :class => 'cross-link'
    %div
      =link_to (image_tag 'slider_images/bryan_baker.jpg', :class => 'nav-thumb', :alt => 'temp-thumb'), '#5', :class => 'cross-link'
    %div
      =link_to (image_tag 'slider_images/cr_higuan_benzema.jpg', :class => 'nav-thumb', :alt => 'temp-thumb'), '#6', :class => 'cross-link'

app/views/home/_tabstrip.html.haml
%p{:class => 's-taber'} Selected Bets
%div{:class => 'tabber'}
  %div{:class => 'tabbertab', :title => 'Soccer'}
    %table{:class => 'table-dbates'}
      %thead
        %tr
          %th Time:Date
          %th First Team Wins
          %th Draw
          %th Second Team Wins
        %tbody
          %tr
            %td{:class => 'match-date'} 5:00 PM 2/14
            %td{:class => 'teams'} 
              %span{:class => 'team-name'}Man. United 
              %span{:class => 'team-odd'} 2.3
            %td{:class => 'teams'} 3.09
            %td{:class => 'teams'} Real Madrid 1.5
          %tr
            %td{:class => 'match-date'} 5:25 PM 2/14
            %td{:class => 'teams'} Man. City 1.21
            %td{:class => 'teams'} 2.42
            %td{:class => 'teams'} Chelsea FC 2.01
          %tr
            %td{:class => 'match-date'} 9:00 PM 2/25
            %td{:class => 'teams'} Udinese 2.90
            %td{:class => 'teams'} 3.35
            %td{:class => 'teams'} SSC Napoli 2.35
          %tr
            %td{:class => 'match-date'} 11:00 PM 2/25
            %td{:class => 'teams'} WestHam Utd 3.30
            %td{:class => 'teams'} 3.30
            %td{:class => 'teams'} Tottenham Hotspur 2.15

  %div{:class => 'tabbertab', :title => 'Tennis'}
    %table{:class => 'table-dbates'}
      %thead
        %tr
          %th Time:Date
          %th Player One Wins
          %th Player Two Wins
        %tbody
          %tr
            %td{:class => 'match-date'} 5:00 PM 2/14
            %td{:class => 'teams'} 
              %span{:class => 'team-name'} Roger Federer
              %span{:class => 'team-odd'} 2.3
            %td{:class => 'teams'} Stanslas Wawrinka 1.5
          %tr
            %td{:class => 'match-date'} 5:25 PM 2/14
            %td{:class => 'teams'} Maria Sharapova 1.21
            %td{:class => 'teams'} Serena Williams 2.01
          %tr
            %td{:class => 'match-date'} 9:00 PM 2/25
            %td{:class => 'teams'}  Maria Kirilenko 2.90
            %td{:class => 'teams'} Sloan Stevens 2.35
          %tr
            %td{:class => 'match-date'} 11:00 PM 2/25
            %td{:class => 'teams'} James Blake 3.30
            %td{:class => 'teams'} Donald Young 2.15

  %div{:class => 'tabbertab', :title => 'Cricket'}
    %h3 This is tab three
    %p Tab three here
  %div{:class => 'tabbertab', :title => 'Rugby'}
    %h3 This is tab four
    %p tab four her
  %div{:class => 'tabbertab'}
    %h3 Basketball
    %p Tab five here

app/views/home/about.html.haml
.container
  .row
    .span9
      %h4 Mission
      %p
        We are dedicated to achieving operational brilliance and providing significant returns for our partners and shareholders.
      %p
        We are dedicated to achieving a well established market position based on longstanding proffesional expertise. Our key possesions being highly specialized and talented staff, excellent management methodologies and a comprehensive approach to business developed on the foundation of knowledge and skills.

      %h4 Values
      %p
        Beginning with our management team, every employee at Grand Victoria limited, our parent company??, operates respecting the dignity of each individual, whether another employee, customer, shareholder, or member of the society. Our values reflect a commitment to our customers through our emphasis on excellence, integrity and the highest degree of ethical behaviour.

app/views/home/coming_soon.html.haml
.container
  .row
    .span
      %h2 Coming Soon!
      %p This feature is in the pipeline
      =link_to 'Go Back To The Home Page', root_path

app/views/home/contact.html.haml
.container
  .row
    .span5
      .contact-form
        %h6 Welcome to the Fortune Bet Help Area.  
        =simple_form_for(@inquiry, :url => inquiry_path, :html => {:class => 'form-horizontal' }) do |f| 
        %p Please remember to select the option that best describes your inquiry. This will help us to more accurately answer your inquiry.
          = f.error_notification
          = f.input :name, :autofocus => true
          = f.input :email, :required => true
          = f.input :phone_number, :required => true
          - options =  Inquiry::INQUIRY_TYPES
          = f.input :inquiry_type, :collection => options, :prompt => "Select type of Inquiry"
          = f.input :message, :as => :text, :required => true, :input_html => { :rows => 12 }
          = f.button :submit, 'Submit', :class => 'btn-primary'

    .span5
      .well
        %h6 Frequently ASked
        %p Optionally you can browse through the inquiries previously made by other customers.
        %div{:class => "container-fluid"}
          %div{:class => "accordion", :id => "accordion2"}
            %div{:class => "accordion-group"}
              %div{:class => "accordion-heading"}
                %a{:href => "#collapseOne", :class => "accordion-toggle", :data => {:toggle => "collapse", :parent => "#accordion2"}}
                  Question 1
              %div{:id => "collapseOne", :class => "accordion-body collapse", :style => "height: 0px;"}
                %div{:class => "accordion-inner"}
                  %div
                    %p
                      Here's where you'll find the answer to question 1

            %div{:class => "accordion-group"}
              %div{:class => "accordion-heading"}
                %a{:href => "#collapseTwo", :class => "accordion-toggle", :data => {:toggle => "collapse", :parent => "#accordion2"}}
                  Question 2
              %div{:id => "collapseTwo", :class => "accordion-body collapse"}
                %div{:class => "accordion-inner"}
                  %div
                    %p
                      Here lies the answer to question 2

            %div{:class => "accordion-group"}
              %div{:class => "accordion-heading"}
                %a{:href => "#collapseThree", :class => "accordion-toggle", :data => {:toggle => "collapse", :parent => "#accordion2"}}
                  Question 3
              %div{:id => "collapseThree", :class => "accordion-body collapse"}
                %div{:class => "inner"}
                  %div
                    %p
                      This part contains the answer to the question specied in question 3 

        %h6 Other contact options
        %ul
          %li Phone Number: +256414693838
          %li Mobile: (0793) 339-935, (0793) 410-555, (0794) 464-939, (0793) 339-934
          %li Email
        %h6 Physical Location
        %p
          Fortune Bet
          %br
          Plot 4, second street
          %br
          Industrial area opposite Euro tyres

app/views/home/index.html.haml
.row-fluid
  %div{:class => 'span2'}
    %div{ :class => 'well' }
      %ul{ :class => 'nav nav-list' }
        %li{ :class => 'nav-header' }
          = render 'all_sports'

  %div{:class => 'span5'}
    %div{:id => 'page-wrap'}
      =render 'slider'

    %div{:id => 'daily-odds'}
      %div{:class => 'well'}
        /=render 'daily_odds'
        =render 'tabstrip'

  %div{:class => 'span5'}
    -#.well
      .btn 
        Betlist/Gamelist
    .well
      =render :partial => 'hot_bets', :locals => {:match => @matches }

app/views/home/privacy.html.haml
.container
  .row
    .span9
      %h1 Privacy policy
      %h5 PRIVACY
      %p
        We believe its an honor for a person to entrust you with their personal information. To that end we take all the measures we can to make sure that your data is safe and secure. 

      %h5 COOKIES
      %p
        This website implements cookies. We may store some information on your computer, laptop, tablet or mobile device when you look at our sites, mobile sites or mobile apps. Cookies allow us to remember things about your visits across our sites so we can improve your user experience. We use them solely for this purpose and we do not collect any other information from your device. We also may use cookies and third party cookies to monitor traffic to the site. We may use flash cookies and third party cookies to help us to show you advertisements which are relevant to your interests based on your use of Our sites.