config/routes.rb
Fortune::Application.routes.draw do

  resources :sports do
    collection do
      get 'soccer'
      get 'tennis'
    end
  end
  get "jobs/index"

  get "jobs/show"

  get "inquiries/new"

  post "inquiries/create"

  get "ticket_draws/new"

  post "ticket_draws/create"

  get "matches/index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users
  resources :users

  get 'home/legal'
  get 'home/privacy'
  get 'home/about'
  get 'home/contact'
  get 'home/coming_soon'

  get 'sports/soccer'

  get 'results/index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/bet_option.rb
class BetOption < ActiveRecord::Base
  attr_accessible :available_for, :name, :number_of_sub_options
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
  INQUIRY_TYPES = ["Customer Service Complaint", "General Inquiry", "Other"].freeze

  attr_accessible :email, :message, :name, :priority, :inquiry_type, :phone_number
  validates_presence_of :email, :message
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates_inclusion_of :inquiry_type, :in => INQUIRY_TYPES

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :category, :description, :location, :qualifications, :title
end

app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :match_date, :player_one, :player_two, :sport, :tournament

  validates_presence_of :match_date, :player_one, :player_two, :sport, :tournament

  has_one :result
end

app/models/news_viewer.rb
class NewsViewer < ActiveRecord::Base
  attr_accessible :author, :body, :excerpt, :title, :media

  #belongs_to :admin_user
  has_attached_file :media, :styles => { :full => "419x282>" }
end

app/models/result.rb
class Result < ActiveRecord::Base
  attr_accessible :match_id, :score

  belongs_to :match
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  attr_accessible :description, :name, :icon

  has_attached_file :icon

  validates_presence_of :name
  validates_attachment_presence :icon
  validates_attachment_content_type :icon, :content_type => ['image/png', 'image/vnd.microsoft.icon']
end

app/models/ticket_draw.rb
class TicketDraw < ActiveRecord::Base
  attr_accessible :email, :name, :ticket_number
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @matches = Match.all
  end
  def legal
  end

  def privacy
  end

  def about
  end

  def contact
  end

  def coming_soon
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(params[:inquiry])
    if @inquiry.save
      redirect_to root_path, :notice => 'Thank you. A response will be sent to your email'
    else
      render :action => 'new'
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cp(path)
    #"current_page" if current_page?(path)
    if current_page?(path)
      "current-page"
    else
      nil
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def jobs_available?
    if @jobs.length > 0
      true
    else
      false
    end
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/ticket_draws_helper.rb
module TicketDrawsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/inquiries/create.html.erb
<h1>Inquiries#create</h1>
<p>Find me in app/views/inquiries/create.html.erb</p>

app/views/inquiries/new.html.haml
.container
  .row
    .span5
      .contact-form
        %h6 Welcome to the Fortune Bet Help Area.  
        %p Please remember to select the option that best describes your inquiry. This will help us to more accurately answer your inquiry.
        =simple_form_for(@inquiry, :url => inquiries_create_path, :html => {:class => 'form-horizontal' }) do |f| 
          = f.error_notification
          = f.input :name, :autofocus => true
          = f.input :email, :required => true
          = f.input :phone_number, :required => true
          - options =  Inquiry::INQUIRY_TYPES
          = f.input :inquiry_type, :collection => options, :prompt => "Select type of Inquiry"
          = f.input :message, :as => :text, :required => true, :input_html => { :rows => 12 }
          = f.button :submit, 'Submit', :class => 'btn-primary'

    .span5
      .well
        %h6 Frequently ASked
        %p Optionally you can browse through the inquiries previously made by other customers.
        %div{:class => "container-fluid"}
          %div{:class => "accordion", :id => "accordion2"}
            %div{:class => "accordion-group"}
              %div{:class => "accordion-heading"}
                %a{:href => "#collapseOne", :class => "accordion-toggle", :data => {:toggle => "collapse", :parent => "#accordion2"}}
                  Question 1
              %div{:id => "collapseOne", :class => "accordion-body collapse", :style => "height: 0px;"}
                %div{:class => "accordion-inner"}
                  %div
                    %p
                      Here's where you'll find the answer to question 1

            %div{:class => "accordion-group"}
              %div{:class => "accordion-heading"}
                %a{:href => "#collapseTwo", :class => "accordion-toggle", :data => {:toggle => "collapse", :parent => "#accordion2"}}
                  Question 2
              %div{:id => "collapseTwo", :class => "accordion-body collapse"}
                %div{:class => "accordion-inner"}
                  %div
                    %p
                      Here lies the answer to question 2

            %div{:class => "accordion-group"}
              %div{:class => "accordion-heading"}
                %a{:href => "#collapseThree", :class => "accordion-toggle", :data => {:toggle => "collapse", :parent => "#accordion2"}}
                  Question 3
              %div{:id => "collapseThree", :class => "accordion-body collapse"}
                %div{:class => "inner"}
                  %div
                    %p
                      This part contains the answer to the question specied in question 3 

        %h6 Other contact options
        %ul
          %li Phone Number: +256414693838
          %li Mobile: 0793339935, 0793410555
          %li Email
        %h6 Physical Location
        %p
          Fortune Bet
          %br
          Plot 4, second street
          %br
          Industrial area opposite Euro tyres