config/routes.rb
Fortune::Application.routes.draw do

  resources :sports do
    collection do
      get 'soccer'
      get 'tennis'
    end
  end
  get "jobs/index"

  get "jobs/show"

  get "inquiries/new"

  post "inquiries/create"

  get "ticket_draws/new"

  post "ticket_draws/create"

  get "matches/index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users
  resources :users

  get 'home/legal'
  get 'home/privacy'
  get 'home/about'
  get 'home/contact'
  get 'home/coming_soon'

  get 'sports/soccer'

  get 'results/index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/bet_option.rb
class BetOption < ActiveRecord::Base
  attr_accessible :available_for, :name, :number_of_sub_options
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
  INQUIRY_TYPES = ["Customer Service Complaint", "General Inquiry", "Other"].freeze

  attr_accessible :email, :message, :name, :priority, :inquiry_type, :phone_number
  validates_presence_of :email, :message
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates_inclusion_of :inquiry_type, :in => INQUIRY_TYPES

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :category, :description, :location, :qualifications, :title
end

app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :match_date, :player_one, :player_two, :sport, :tournament

  validates_presence_of :match_date, :player_one, :player_two, :sport, :tournament

  has_one :result
end

app/models/news_viewer.rb
class NewsViewer < ActiveRecord::Base
  attr_accessible :author, :body, :excerpt, :title, :media

  #belongs_to :admin_user
  has_attached_file :media, :styles => { :full => "419x282>" }
end

app/models/result.rb
class Result < ActiveRecord::Base
  attr_accessible :match_id, :score

  belongs_to :match
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  attr_accessible :description, :name, :icon

  has_attached_file :icon

  validates_presence_of :name
  validates_attachment_presence :icon
  validates_attachment_content_type :icon, :content_type => ['image/png', 'image/vnd.microsoft.icon']
end

app/models/ticket_draw.rb
class TicketDraw < ActiveRecord::Base
  attr_accessible :email, :name, :ticket_number
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @matches = Match.all
  end
  def legal
  end

  def privacy
  end

  def about
  end

  def contact
  end

  def coming_soon
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cp(path)
    #"current_page" if current_page?(path)
    if current_page?(path)
      "current-page"
    else
      nil
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def jobs_available?
    if @jobs.length > 0
      true
    else
      false
    end
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
=render 'layouts/locations'
%hr
.centered-content
  %nav{:id => 'footer-navi'}
    = link_to 'Rules and Regulations', home_legal_path
    = link_to 'Privacy', home_privacy_path
    = link_to 'About Us', home_about_path
    = link_to 'Contact', inquiries_new_path
    = link_to 'Careers', jobs_index_path
    /= link_to 'Facebook', '#'
    /= link_to 'Twitter', '#'
    /= link_to 'Google+', '#'
    /= link_to 'Linkedin', '#'

app/views/layouts/_locations.html.haml
%br
%div{:id => 'myCollapsibleExample'}
  %a{:href => '#demo', :data => {:toggle => 'collapse'}}
    =image_tag 'play_6x8.png'
    Our Betting outlets
%div{:id => 'demo', :class => 'collapse'}
  %div{:class => 'row-fluid address-foot'}
    %div{:class => 'span3 foot'}
      %address Fort Portal
      %address Bundibugyo
      %address Kasana
      %address Grand Players Second Street(VIP)
      %address Arua
      %address Entebbe Kitoro
      %address Busia
    %div{:class => 'span3 foot'}
      %address Bwera Kasese
      %address Mityana
      %address Luwero
      %address Grand Players Lubowa(VIP)
      %address Gulu
      %address Stella
      %address Gaba
    %div{:class => 'span3 foot'}
      %address Mubende
      %address Natete
      %address Kireka
      %address Soroti
      %address Nansana
      %address Jinja
      %address Kalerwe
    %div{:class => 'span3 foot'}
      %address Rubaga
      %address Kawempe
      %address Kololo courts Hotel
      %address Lira
      %address Bayita
      %address Ben Kiwanuka, container village
      %address Kamwokya

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to (image_tag "logo.png", :size => "141x100"), root_path, :class => 'brand'
%nav{ :class => 'navbar-text pull-right' }
  - if user_signed_in?
    = link_to('Logout', destroy_user_session_path, :method=>'delete')
  - else
    = link_to('Login', new_user_session_path)
  - if user_signed_in?
    = link_to('Edit account', edit_user_registration_path)
  - else
    = link_to('Register now!', new_user_registration_path)
  =link_to (image_tag 'slogan.png'), 'http://www.imperialholding.eu/'
%ul.nav
  %li= link_to 'All Sports', matches_index_path, :class => cp(matches_index_path)
  %li= link_to 'Results' , results_index_path, :class => cp(results_index_path)
  %li= link_to 'Enter Ticket Draw', ticket_draws_new_path, :class => cp(ticket_draws_new_path)
  %li= link_to 'Live Betting', home_coming_soon_path, :class => cp(home_coming_soon_path)
  %li= link_to 'Non Sports Betting', home_coming_soon_path, :class => cp(home_coming_soon_path)
  %form{:class => 'navbar-search pull-right'}
    %input{:type => 'text', :class => 'search-query', :placeholder => 'Search'}
  %span{:class => 'text-warning release'} Alpha Version

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Fortune Bet"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag "home", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar
      %nav.navbar-inner
        .container-fluid
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container-fluid
        .content
          .row-fluid
            .span12
              = render 'layouts/messages'
              = yield
      %footer
        = render 'layouts/footer'